apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: opscraft
data:
  SERVICE_NAME: "auth-service"
  SERVICE_PORT: "8001"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  KAFKA_TOPIC_USER_EVENTS: "user-events"
