apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: opscraft
data:
  SERVICE_NAME: "notification-service"
  SERVICE_PORT: "8005"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
