apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-config
  namespace: opscraft
data:
  SERVICE_NAME: "secret-service"
  SERVICE_PORT: "8004"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  KAFKA_TOPIC_SECRET_EVENTS: "secret-events"
